name: KukaPickObject

env:
  numEnvs: 256
  envSpacing: 1.5
  episodeLength: 500

  obj_type: banana
  object_pos_init: [0.5, 0.0]
  object_pos_delta: [0.1, 0.2]

  goal_height: 0.8

  obs_type: pixels
  im_size: 224

  cam:
    w: 298
    h: 224
    fov: 120
    ss: 2
    loc_p: [0.05, 0.0, 0.02]
    loc_r: [0, -90.0, 0.0]

  dofVelocityScale: 0.1
  actionScale: 7.5

  fingerDistRewardScale: 0.04
  thumbDistRewardScale: 0.08
  liftBonusRewardScale: 4.0
  goalDistRewardScale: 1.28
  goalBonusRewardScale: 4.0
  actionPenaltyScale: 0.01

  asset:
    assetRoot: "assets"
    assetFileNameKuka: "urdf/kuka_allegro_description/kuka_allegro.urdf"

sim:
  substeps: 1
  physx:
    num_threads: 4
    solver_type: 1
    num_position_iterations: 12
    num_velocity_iterations: 1
    contact_offset: 0.005
    rest_offset: 0.0
    bounce_threshold_velocity: 0.2
    max_depenetration_velocity: 1000.0
    default_buffer_size_multiplier: 5.0
    always_use_articulations: False

task:
  randomize: False
